---
stages:
  - test
  - release

lint:
  stage: test
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  script:
    - helm version
    - helm dependency update
    - helm lint --strict

release-chart:
  stage: release
  image:
    name: curlimages/curl:latest
    entrypoint: [""]
  script:
    - >-
      curl -X POST -F token=${CHARTS_TRIGGER_TOKEN} -F ref=master
      -F variables[CHART_NAME]=${CI_PROJECT_NAME}
      -F variables[CHART_VERSION]=${CI_COMMIT_TAG}
      https://git.boo.tc/api/v4/projects/20/trigger/pipeline
  only:
    - tags

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
