owner: netbox-community
repo: netbox-chart
remote: origin
target-branch: main
sign: true
key: builds@netboxlabs.com
keyring: ~/.cr-gpg/secring.gpg
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: "--timeout 15m"
generate-release-notes: true
