apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: netbox
      protocol: TCP
      name: netbox
  selector:
    {{- include "netbox.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
