apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  configuration.py: |-
    {{ .Files.Get "files/configuration.py" | nindent 4 }}

  netbox.yaml: |-
    ALLOWED_HOSTS: {{ toJson .Values.allowedHosts }}
    ALLOWED_HOSTS_INCLUDES_POD_ID: {{ .Values.allowedHostsIncludesPodIP }}

    DATABASES:
      default:
        {{- if .Values.postgresql.enabled }}
        HOST: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql | quote }}
        USER: {{ include "postgresql.v1.username" .Subcharts.postgresql | quote }}
        NAME: {{ include "postgresql.v1.database" .Subcharts.postgresql | quote }}
        PORT: {{ include "postgresql.v1.service.port" .Subcharts.postgresql | int }}
        {{- else }}
        HOST: {{ .Values.externalDatabase.host | quote }}
        USER: {{ .Values.externalDatabase.username | quote }}
        NAME: {{ .Values.externalDatabase.database | quote }}
        PORT: {{ .Values.externalDatabase.port | int }}
        {{- end }}
        ENGINE: {{ .Values.externalDatabase.engine | quote }}
        OPTIONS: {{- include "common.tplvalues.render" (dict "value" .Values.externalDatabase.options "context" $) | nindent 10 }}
        CONN_MAX_AGE: {{ .Values.externalDatabase.connMaxAge | int }}
        DISABLE_SERVER_SIDE_CURSORS: {{ toJson .Values.externalDatabase.disableServerSideCursors }}
      {{- range $key, $db := .Values.additionalDatabases }}
      {{ $key }}:
        ENGINE: {{ $db.engine | quote }}
        NAME: {{ $db.database | quote }}
        USER: {{ $db.username | quote }}
        HOST: {{ $db.host | quote }}
        PORT: {{ $db.port | int }}
        CONN_MAX_AGE: {{ $db.connMaxAge | int }}
        OPTIONS: {{- include "common.tplvalues.render" (dict "value" $db.options "context" $) | nindent 10 }}
        DISABLE_SERVER_SIDE_CURSORS: {{ toJson $db.disableServerSideCursors }}
      {{- end }}

    ADMINS: {{ toJson .Values.admins }}
    ALLOW_TOKEN_RETRIEVAL: {{ toJson .Values.allowTokenRetrieval }}
    AUTH_PASSWORD_VALIDATORS: {{ toJson .Values.authPasswordValidators }}
    ALLOWED_URL_SCHEMES: {{ toJson .Values.allowedUrlSchemes }}
    BANNER_TOP: {{ .Values.banner.top | quote }}
    BANNER_BOTTOM: {{ .Values.banner.bottom | quote }}
    BANNER_LOGIN: {{ .Values.banner.login | quote }}
    BASE_PATH: {{ .Values.basePath | quote }}
    CHANGELOG_RETENTION: {{ int .Values.changelogRetention }}
    CUSTOM_VALIDATORS: {{ toJson .Values.customValidators }}
    DEFAULT_USER_PREFERENCES: {{ toJson .Values.defaultUserPreferences }}
    CORS_ORIGIN_ALLOW_ALL: {{ toJson .Values.cors.originAllowAll }}
    CORS_ORIGIN_WHITELIST: {{ toJson .Values.cors.originWhitelist }}
    CORS_ORIGIN_REGEX_WHITELIST: {{ toJson .Values.cors.originRegexWhitelist }}
    CSRF_TRUSTED_ORIGINS: {{ toJson .Values.csrf.trustedOrigins }}
    DATA_UPLOAD_MAX_MEMORY_SIZE: {{ int .Values.dataUploadMaxMemorySize }}
    DEBUG: {{ toJson .Values.debug }}
    DEFAULT_LANGUAGE: {{ .Values.defaultLanguage | quote }}

    EMAIL:
      SERVER: {{ .Values.email.server | quote }}
      PORT: {{ .Values.email.port | int }}
      USERNAME: {{ .Values.email.username | quote }}
      USE_SSL: {{ toJson .Values.email.useSSL }}
      USE_TLS: {{ toJson .Values.email.useTLS }}
      SSL_CERTFILE: {{ .Values.email.sslCertFile | quote }}
      SSL_KEYFILE: {{ .Values.email.sslKeyFile | quote }}
      TIMEOUT: {{ .Values.email.timeout | int }}
      FROM_EMAIL: {{ toJson .Values.email.from }}

    ENFORCE_GLOBAL_UNIQUE: {{ toJson .Values.enforceGlobalUnique }}
    EXEMPT_VIEW_PERMISSIONS: {{ toJson .Values.exemptViewPermissions }}
    FIELD_CHOICES: {{ toJson .Values.fieldChoices }}
    FILE_UPLOAD_MAX_MEMORY_SIZE: {{ int .Values.fileUploadMaxMemorySize }}
    GRAPHQL_ENABLED: {{ toJson .Values.graphQlEnabled }}
    HTTP_PROXIES: {{ toJson .Values.httpProxies }}
    INTERNAL_IPS: {{ toJson .Values.internalIPs }}
    JOB_RETENTION: {{ int .Values.jobRetention }}
    LOGGING: {{ toJson .Values.logging }}
    LOGIN_PERSISTENCE: {{ toJson .Values.loginPersistence }}
    LOGIN_REQUIRED: {{ toJson .Values.loginRequired }}
    LOGIN_TIMEOUT: {{ int .Values.loginTimeout }}
    LOGOUT_REDIRECT_URL: {{ .Values.logoutRedirectUrl | quote }}
    MAINTENANCE_MODE: {{ toJson .Values.maintenanceMode }}
    MAPS_URL: {{ .Values.mapsUrl | quote }}
    MAX_PAGE_SIZE: {{ int .Values.maxPageSize }}
    MEDIA_ROOT: /opt/netbox/netbox/media
    STORAGES: {{ toJson .Values.storages }}
    METRICS_ENABLED: {{ toJson .Values.metrics.enabled }}
    PAGINATE_COUNT: {{ int .Values.paginateCount }}
    PLUGINS: {{ toJson .Values.plugins }}
    PLUGINS_CONFIG: {{ toJson .Values.pluginsConfig }}
    POWERFEED_DEFAULT_AMPERAGE: {{ int .Values.powerFeedDefaultAmperage }}
    POWERFEED_DEFAULT_MAX_UTILIZATION: {{ int .Values.powerFeedMaxUtilisation }}
    POWERFEED_DEFAULT_VOLTAGE: {{ int .Values.powerFeedDefaultVoltage }}
    PREFER_IPV4: {{ toJson .Values.preferIPv4 }}
    RACK_ELEVATION_DEFAULT_UNIT_HEIGHT: {{ int .Values.rackElevationDefaultUnitHeight }}
    RACK_ELEVATION_DEFAULT_UNIT_WIDTH: {{ int .Values.rackElevationDefaultUnitWidth }}
    REMOTE_AUTH_ENABLED: {{ toJson .Values.remoteAuth.enabled }}
    REMOTE_AUTH_BACKEND: {{ toJson .Values.remoteAuth.backends }}
    REMOTE_AUTH_HEADER: {{ .Values.remoteAuth.header | quote }}
    REMOTE_AUTH_USER_FIRST_NAME: {{ .Values.remoteAuth.userFirstName | quote }}
    REMOTE_AUTH_USER_LAST_NAME: {{ .Values.remoteAuth.userLastName | quote }}
    REMOTE_AUTH_USER_EMAIL: {{ .Values.remoteAuth.userEmail | quote }}
    REMOTE_AUTH_AUTO_CREATE_USER: {{ toJson .Values.remoteAuth.autoCreateUser }}
    REMOTE_AUTH_AUTO_CREATE_GROUPS: {{ toJson .Values.remoteAuth.autoCreateGroups }}
    REMOTE_AUTH_DEFAULT_GROUPS: {{ toJson .Values.remoteAuth.defaultGroups }}
    REMOTE_AUTH_DEFAULT_PERMISSIONS: {{ toJson .Values.remoteAuth.defaultPermissions }}
    REMOTE_AUTH_GROUP_SYNC_ENABLED: {{ toJson .Values.remoteAuth.groupSyncEnabled }}
    REMOTE_AUTH_GROUP_HEADER: {{ .Values.remoteAuth.groupHeader | quote }}
    REMOTE_AUTH_SUPERUSER_GROUPS: {{ toJson .Values.remoteAuth.superuserGroups }}
    REMOTE_AUTH_SUPERUSERS: {{ toJson .Values.remoteAuth.superusers }}
    REMOTE_AUTH_STAFF_GROUPS: {{ toJson .Values.remoteAuth.staffGroups }}
    REMOTE_AUTH_STAFF_USERS: {{ toJson .Values.remoteAuth.staffUsers }}
    REMOTE_AUTH_GROUP_SEPARATOR: {{ .Values.remoteAuth.groupSeparator | quote }}
    RELEASE_CHECK_URL: {{ toJson .Values.releaseCheck.url }}

    REDIS:
      tasks:
        {{- if (include "netbox.tasksDatabase.sentinels" .) }}
        SENTINELS: {{ include "netbox.tasksDatabase.sentinels" . }}
        SENTINEL_SERVICE: {{ ternary .Values.valkey.sentinel.primarySet .Values.tasksDatabase.sentinelService (empty .Values.tasksDatabase.sentinels) | quote }}
        SENTINEL_TIMEOUT: {{ .Values.tasksDatabase.sentinelTimeout | int }}
        {{- else if .Values.valkey.enabled }}
        HOST: {{ printf "%s-primary" (include "common.names.fullname" .Subcharts.valkey) | quote }}
        PORT: {{ .Values.valkey.primary.service.ports.valkey | int }}
        {{- else }}
        HOST: {{ .Values.tasksDatabase.host | quote }}
        PORT: {{ .Values.tasksDatabase.port | int }}
        {{- end }}
        USERNAME: {{ .Values.tasksDatabase.username | quote }}
        DATABASE: {{ int .Values.tasksDatabase.database }}
        SSL: {{ toJson .Values.tasksDatabase.ssl }}
        INSECURE_SKIP_TLS_VERIFY: {{ toJson .Values.tasksDatabase.insecureSkipTlsVerify }}
        CA_CERT_PATH: {{ .Values.tasksDatabase.caCertPath | quote }}
      caching:
        {{- if (include "netbox.cachingDatabase.sentinels" .) }}
        SENTINELS: {{ include "netbox.cachingDatabase.sentinels" . }}
        SENTINEL_SERVICE: {{ ternary .Values.valkey.sentinel.primarySet .Values.cachingDatabase.sentinelService (empty .Values.cachingDatabase.sentinels) | quote }}
        SENTINEL_TIMEOUT: {{ .Values.cachingDatabase.sentinelTimeout | int }}
        {{- else if .Values.valkey.enabled }}
        HOST: {{ printf "%s-primary" (include "common.names.fullname" .Subcharts.valkey) | quote }}
        PORT: {{ .Values.valkey.primary.service.ports.valkey | int }}
        {{- else }}
        HOST: {{ .Values.cachingDatabase.host | quote }}
        PORT: {{ .Values.cachingDatabase.port | int}}
        {{- end }}
        USERNAME: {{ .Values.cachingDatabase.username | quote }}
        DATABASE: {{ int .Values.cachingDatabase.database }}
        SSL: {{ toJson .Values.cachingDatabase.ssl }}
        INSECURE_SKIP_TLS_VERIFY: {{ toJson .Values.cachingDatabase.insecureSkipTlsVerify }}
        CA_CERT_PATH: {{ .Values.cachingDatabase.caCertPath | quote }}

    REPORTS_ROOT: /opt/netbox/netbox/reports
    RQ_DEFAULT_TIMEOUT: {{ .Values.rqDefaultTimeout | int }}
    SCRIPTS_ROOT: /opt/netbox/netbox/scripts
    CSRF_COOKIE_NAME: {{ .Values.csrf.cookieName | quote }}
    SESSION_COOKIE_NAME: {{ .Values.sessionCookieName }}
    ENABLE_LOCALIZATION: {{ toJson .Values.enableLocalization }}
    TIME_ZONE: {{ .Values.timeZone | quote }}
    DATE_FORMAT: {{ .Values.dateFormat | quote }}
    SHORT_DATE_FORMAT: {{ .Values.shortDateFormat | quote }}
    TIME_FORMAT: {{ .Values.timeFormat | quote }}
    SHORT_TIME_FORMAT: {{ .Values.shortTimeFormat | quote }}
    DATETIME_FORMAT: {{ .Values.dateTimeFormat | quote }}
    SHORT_DATETIME_FORMAT: {{ .Values.shortDateTimeFormat | quote }}

  {{- if has "netbox.authentication.LDAPBackend" .Values.remoteAuth.backends }}
  ldap_config.py: |-
    {{ .Files.Get "files/ldap_config.py" | nindent 4 }}

  ldap.yaml: |-
    AUTH_LDAP_SERVER_URI: {{ .Values.remoteAuth.ldap.serverUri | quote }}
    AUTH_LDAP_BIND_DN: {{ .Values.remoteAuth.ldap.bindDn | quote }}
    AUTH_LDAP_START_TLS: {{ toJson .Values.remoteAuth.ldap.startTls }}
    LDAP_IGNORE_CERT_ERRORS: {{ toJson .Values.remoteAuth.ldap.ignoreCertErrors }}
    {{- if .Values.remoteAuth.ldap.caCertDir }}
    LDAP_CA_CERT_DIR: {{ .Values.remoteAuth.ldap.caCertDir | quote }}
    {{- end }}
    {{- if .Values.remoteAuth.ldap.caCertData }}
    LDAP_CA_CERT_FILE: /etc/netbox/config/ldap/ldap_ca.crt
    {{- end }}
    AUTH_LDAP_USER_DN_TEMPLATE: {{ default nil .Values.remoteAuth.ldap.userDnTemplate }}
    AUTH_LDAP_USER_SEARCH_BASEDN: {{ .Values.remoteAuth.ldap.userSearchBaseDn | quote }}
    AUTH_LDAP_USER_SEARCH_ATTR: {{ .Values.remoteAuth.ldap.userSearchAttr | quote }}
    AUTH_LDAP_GROUP_SEARCH_BASEDN: {{ .Values.remoteAuth.ldap.groupSearchBaseDn | quote }}
    AUTH_LDAP_GROUP_SEARCH_CLASS: {{ .Values.remoteAuth.ldap.groupSearchClass | quote }}
    AUTH_LDAP_GROUP_TYPE: {{ .Values.remoteAuth.ldap.groupType | quote }}
    AUTH_LDAP_FIND_GROUP_PERMS: {{ toJson .Values.remoteAuth.ldap.findGroupPerms }}
    AUTH_LDAP_MIRROR_GROUPS: {{ toJson .Values.remoteAuth.ldap.mirrorGroups }}
    AUTH_LDAP_MIRROR_GROUPS_EXCEPT: {{ toJson .Values.remoteAuth.ldap.mirrorGroupsExcept }}
    AUTH_LDAP_CACHE_TIMEOUT: {{ int .Values.remoteAuth.ldap.cacheTimeout }}

    AUTH_LDAP_REQUIRE_GROUP_LIST: {{ toJson .Values.remoteAuth.ldap.requireGroupDn }}
    AUTH_LDAP_IS_ADMIN_LIST: {{ toJson .Values.remoteAuth.ldap.isAdminDn }}
    AUTH_LDAP_IS_SUPERUSER_LIST: {{ toJson .Values.remoteAuth.ldap.isSuperUserDn }}

    # Populate the Django user from the LDAP directory.
    AUTH_LDAP_USER_ATTR_MAP:
      first_name: {{ .Values.remoteAuth.ldap.attrFirstName | quote }}
      last_name: {{ .Values.remoteAuth.ldap.attrLastName | quote }}
      email: {{ .Values.remoteAuth.ldap.attrMail | quote }}

  {{- if .Values.remoteAuth.ldap.caCertData }}
  ldap_ca.crt: {{- toYaml .Values.remoteAuth.ldap.caCertData | indent 4 }}
  {{- end }}
  {{- end }}

  {{- if .Values.overrideUnitConfig }}
  nginx-unit.json: |-
    {{- toPrettyJson .Values.overrideUnitConfig | nindent 4 }}
  {{- end }}

  {{- range $index, $config := .Values.extraConfig }}
  {{- if $config.values }}
  {{ printf "extra-%d.yaml" $index }}: |-
    {{- include "common.tplvalues.render" (dict "value" $config.values "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}
